import { Game } from "../types/games";

export const games: Game[] = [
  {
    id: "g001",
    name: "Super Mario Bros.",
    system: "nes",
    genre: ["Platformer"],
    releaseYear: 1985,
    region: "NTSC-J",
    coverArt: "/covers/g001.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.2,
    playtimeMinutes: 1141,
    lastPlayed: "2026-01-24",
    favorite: true,
    installed: true,
    players: 1,
  },
  {
    id: "g002",
    name: "Super Mario Bros. 3",
    system: "nes",
    genre: ["Platformer"],
    releaseYear: 1988,
    region: "NTSC-U",
    coverArt: "/covers/g002.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.6,
    playtimeMinutes: 910,
    lastPlayed: "2026-01-03",
    favorite: true,
    installed: true,
    players: 2,
  },
  {
    id: "g003",
    name: "The Legend of Zelda",
    system: "nes",
    genre: ["Action", "Adventure"],
    releaseYear: 1986,
    region: "NTSC-U",
    coverArt: "/covers/g003.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.5,
    playtimeMinutes: 41,
    lastPlayed: "2026-05-26",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g004",
    name: "Metroid",
    system: "nes",
    genre: ["Action", "Adventure"],
    releaseYear: 1986,
    region: "NTSC-U",
    coverArt: "/covers/g004.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.4,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: false,
    players: 1,
  },
  {
    id: "g005",
    name: "Mega Man 2",
    system: "nes",
    genre: ["Action", "Platformer"],
    releaseYear: 1988,
    region: "NTSC-J",
    coverArt: "/covers/g005.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.8,
    playtimeMinutes: 1423,
    lastPlayed: "2026-06-28",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g006",
    name: "Mega Man 3",
    system: "nes",
    genre: ["Action", "Platformer"],
    releaseYear: 1990,
    region: "NTSC-U",
    coverArt: "/covers/g006.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.2,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: false,
    players: 1,
  },
  {
    id: "g007",
    name: "Castlevania",
    system: "nes",
    genre: ["Action", "Platformer"],
    releaseYear: 1986,
    region: "NTSC-U",
    coverArt: "/covers/g007.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.3,
    playtimeMinutes: 802,
    lastPlayed: "2026-06-19",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g008",
    name: "Castlevania III: Dracula's Curse",
    system: "nes",
    genre: ["Action", "Platformer"],
    releaseYear: 1989,
    region: "NTSC-U",
    coverArt: "/covers/g008.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.9,
    playtimeMinutes: 428,
    lastPlayed: "2026-04-28",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g009",
    name: "Punch-Out!!",
    system: "nes",
    genre: ["Sports", "Fighting"],
    releaseYear: 1987,
    region: "NTSC-U",
    coverArt: "/covers/g009.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.2,
    playtimeMinutes: 1108,
    lastPlayed: "2026-04-22",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g010",
    name: "Kirby's Adventure",
    system: "nes",
    genre: ["Platformer"],
    releaseYear: 1993,
    region: "NTSC-J",
    coverArt: "/covers/g010.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.7,
    playtimeMinutes: 1908,
    lastPlayed: "2026-04-06",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g011",
    name: "DuckTales",
    system: "nes",
    genre: ["Platformer"],
    releaseYear: 1989,
    region: "NTSC-U",
    coverArt: "/covers/g011.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.8,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g012",
    name: "Contra",
    system: "nes",
    genre: ["Run and Gun"],
    releaseYear: 1988,
    region: "NTSC-U",
    coverArt: "/covers/g012.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.9,
    playtimeMinutes: 1307,
    lastPlayed: "2026-01-26",
    favorite: false,
    installed: true,
    players: 2,
  },
  {
    id: "g013",
    name: "Double Dragon II: The Revenge",
    system: "nes",
    genre: ["Beat em up"],
    releaseYear: 1989,
    region: "NTSC-J",
    coverArt: "/covers/g013.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.8,
    playtimeMinutes: 1894,
    lastPlayed: "2026-07-21",
    favorite: true,
    installed: true,
    players: 2,
  },
  {
    id: "g014",
    name: "Ninja Gaiden",
    system: "nes",
    genre: ["Action", "Platformer"],
    releaseYear: 1989,
    region: "NTSC-U",
    coverArt: "/covers/g014.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.5,
    playtimeMinutes: 913,
    lastPlayed: "2026-07-12",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g015",
    name: "Final Fantasy",
    system: "nes",
    genre: ["RPG"],
    releaseYear: 1990,
    region: "PAL",
    coverArt: "/covers/g015.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.2,
    playtimeMinutes: 670,
    lastPlayed: "2026-03-21",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g016",
    name: "Dragon Warrior",
    system: "nes",
    genre: ["RPG"],
    releaseYear: 1989,
    region: "NTSC-U",
    coverArt: "https://cdn2.steamgriddb.com/thumb/d927d8f806391cb87ae1ad0479ebf7d5.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.1,
    playtimeMinutes: 1044,
    lastPlayed: "2026-08-17",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g017",
    name: "Tetris",
    system: "nes",
    genre: ["Puzzle"],
    releaseYear: 1989,
    region: "PAL",
    coverArt: "https://cdn2.steamgriddb.com/thumb/40e6cc4c5bf9c2a97b8220b33086e2d1.jpg",
    backdropArt: "https://cdn2.steamgriddb.com/hero/062ddb6c727310e76b6200b7c71f63b5.png",
    fileSizeMB: 0.4,
    playtimeMinutes: 1107,
    lastPlayed: "2026-09-25",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g018",
    name: "Excitebike",
    system: "nes",
    genre: ["Racing"],
    releaseYear: 1985,
    region: "NTSC-J",
    coverArt: "/covers/g018.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.7,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g019",
    name: "Ice Climber",
    system: "nes",
    genre: ["Platformer"],
    releaseYear: 1985,
    region: "NTSC-J",
    coverArt: "/covers/g019.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.8,
    playtimeMinutes: 2094,
    lastPlayed: "2026-05-27",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g020",
    name: "River City Ransom",
    system: "nes",
    genre: ["Beat em up", "RPG"],
    releaseYear: 1989,
    region: "NTSC-U",
    coverArt: "/covers/g020.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.4,
    playtimeMinutes: 1501,
    lastPlayed: "2026-01-04",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g021",
    name: "Super Mario World",
    system: "snes",
    genre: ["Platformer"],
    releaseYear: 1990,
    region: "NTSC-U",
    coverArt: "/covers/g021.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 2.4,
    playtimeMinutes: 2005,
    lastPlayed: "2026-02-03",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g022",
    name: "Super Mario Kart",
    system: "snes",
    genre: ["Racing"],
    releaseYear: 1992,
    region: "NTSC-U",
    coverArt: "https://cdn2.steamgriddb.com/thumb/faf6310027c2c505c8e5654c7da7dd47.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 3.9,
    playtimeMinutes: 1100,
    lastPlayed: "2026-09-06",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g023",
    name: "The Legend of Zelda: A Link to the Past",
    system: "snes",
    genre: ["Action", "Adventure", "RPG"],
    releaseYear: 1991,
    region: "NTSC-U",
    coverArt: "/covers/g023.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.7,
    playtimeMinutes: 2134,
    lastPlayed: "2026-06-15",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g024",
    name: "Super Metroid",
    system: "snes",
    genre: ["Action", "Adventure"],
    releaseYear: 1994,
    region: "NTSC-U",
    coverArt: "/covers/g024.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.7,
    playtimeMinutes: 917,
    lastPlayed: "2026-04-19",
    favorite: true,
    installed: true,
    players: 1,
  },
  {
    id: "g025",
    name: "Chrono Trigger",
    system: "snes",
    genre: ["RPG"],
    releaseYear: 1995,
    region: "NTSC-U",
    coverArt: "/covers/g025.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1.2,
    playtimeMinutes: 2120,
    lastPlayed: "2026-06-03",
    favorite: true,
    installed: true,
    players: 1,
  },
  {
    id: "g026",
    name: "Final Fantasy VI",
    system: "snes",
    genre: ["RPG"],
    releaseYear: 1994,
    region: "PAL",
    coverArt: "/covers/g026.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.8,
    playtimeMinutes: 1952,
    lastPlayed: "2026-08-08",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g027",
    name: "Super Castlevania IV",
    system: "snes",
    genre: ["Action", "Platformer"],
    releaseYear: 1991,
    region: "PAL",
    coverArt: "/covers/g027.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.8,
    playtimeMinutes: 236,
    lastPlayed: "2026-07-15",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g028",
    name: "Donkey Kong Country",
    system: "snes",
    genre: ["Platformer"],
    releaseYear: 1994,
    region: "PAL",
    coverArt: "/covers/g028.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 2.0,
    playtimeMinutes: 799,
    lastPlayed: "2026-02-08",
    favorite: true,
    installed: true,
    players: 2,
  },
  {
    id: "g029",
    name: "Donkey Kong Country 2: Diddy's Kong Quest",
    system: "snes",
    genre: ["Platformer"],
    releaseYear: 1995,
    region: "NTSC-U",
    coverArt: "/covers/g029.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 2.4,
    playtimeMinutes: 2269,
    lastPlayed: "2026-02-15",
    favorite: true,
    installed: true,
    players: 1,
  },
  {
    id: "g030",
    name: "Star Fox",
    system: "snes",
    genre: ["Shooter"],
    releaseYear: 1993,
    region: "NTSC-U",
    coverArt: "/covers/g030.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1.9,
    playtimeMinutes: 1679,
    lastPlayed: "2026-04-06",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g031",
    name: "Mega Man X",
    system: "snes",
    genre: ["Action", "Platformer"],
    releaseYear: 1993,
    region: "PAL",
    coverArt: "/covers/g031.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1.9,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g032",
    name: "Super Mario RPG: Legend of the Seven Stars",
    system: "snes",
    genre: ["RPG"],
    releaseYear: 1996,
    region: "NTSC-J",
    coverArt: "https://cdn2.steamgriddb.com/thumb/c6b17013ccaaa75237f8bfda6a1f25e2.jpg",
    backdropArt: "https://cdn2.steamgriddb.com/hero/7482d965e9c3156079b7ea6423fd41fa.jpg",
    fileSizeMB: 3.9,
    playtimeMinutes: 2008,
    lastPlayed: "2026-09-22",
    favorite: true,
    installed: true,
    players: 1,
  },
  {
    id: "g033",
    name: "EarthBound",
    system: "snes",
    genre: ["RPG"],
    releaseYear: 1994,
    region: "NTSC-J",
    coverArt: "/covers/g033.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 2.3,
    playtimeMinutes: 1299,
    lastPlayed: "2026-01-24",
    favorite: true,
    installed: true,
    players: 1,
  },
  {
    id: "g034",
    name: "Kirby Super Star",
    system: "snes",
    genre: ["Platformer"],
    releaseYear: 1996,
    region: "NTSC-U",
    coverArt: "/covers/g034.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.8,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: false,
    players: 1,
  },
  {
    id: "g035",
    name: "F-Zero",
    system: "snes",
    genre: ["Racing"],
    releaseYear: 1990,
    region: "NTSC-U",
    coverArt: "/covers/g035.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 2.5,
    playtimeMinutes: 506,
    lastPlayed: "2026-04-13",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g036",
    name: "Contra III: The Alien Wars",
    system: "snes",
    genre: ["Run and Gun"],
    releaseYear: 1992,
    region: "NTSC-U",
    coverArt: "/covers/g036.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1.2,
    playtimeMinutes: 2330,
    lastPlayed: "2026-07-22",
    favorite: false,
    installed: true,
    players: 2,
  },
  {
    id: "g037",
    name: "Street Fighter II Turbo",
    system: "snes",
    genre: ["Fighting"],
    releaseYear: 1993,
    region: "PAL",
    coverArt: "/covers/g037.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 3.8,
    playtimeMinutes: 1243,
    lastPlayed: "2026-03-22",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g038",
    name: "Super Punch-Out!!",
    system: "snes",
    genre: ["Sports", "Fighting"],
    releaseYear: 1994,
    region: "NTSC-U",
    coverArt: "/covers/g038.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 3.8,
    playtimeMinutes: 2217,
    lastPlayed: "2026-02-03",
    favorite: true,
    installed: true,
    players: 1,
  },
  {
    id: "g039",
    name: "Super Mario World 2: Yoshi's Island",
    system: "snes",
    genre: ["Platformer"],
    releaseYear: 1995,
    region: "NTSC-J",
    coverArt: "/covers/g039.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1.6,
    playtimeMinutes: 661,
    lastPlayed: "2026-06-10",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g040",
    name: "Secret of Mana",
    system: "snes",
    genre: ["RPG"],
    releaseYear: 1993,
    region: "NTSC-U",
    coverArt: "/covers/g040.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 2.4,
    playtimeMinutes: 1098,
    lastPlayed: "2026-02-05",
    favorite: true,
    installed: true,
    players: 3,
  },
  {
    id: "g041",
    name: "Super Mario 64",
    system: "n64",
    genre: ["Platformer"],
    releaseYear: 1996,
    region: "NTSC-U",
    coverArt: "/covers/g041.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 29.4,
    playtimeMinutes: 1096,
    lastPlayed: "2026-06-07",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g042",
    name: "The Legend of Zelda: Ocarina of Time",
    system: "n64",
    genre: ["Action", "Adventure", "RPG"],
    releaseYear: 1998,
    region: "NTSC-U",
    coverArt: "/covers/g042.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 11.7,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g043",
    name: "The Legend of Zelda: Majora's Mask",
    system: "n64",
    genre: ["Action", "Adventure", "RPG"],
    releaseYear: 2000,
    region: "NTSC-J",
    coverArt: "/covers/g043.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 23.8,
    playtimeMinutes: 1087,
    lastPlayed: "2026-03-21",
    favorite: true,
    installed: true,
    players: 1,
  },
  {
    id: "g044",
    name: "GoldenEye 007",
    system: "n64",
    genre: ["FPS"],
    releaseYear: 1997,
    region: "NTSC-J",
    coverArt: "/covers/g044.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 28.7,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g045",
    name: "Mario Kart 64",
    system: "n64",
    genre: ["Racing"],
    releaseYear: 1996,
    region: "NTSC-U",
    coverArt: "/covers/g045.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 19.5,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: true,
    players: 4,
  },
  {
    id: "g046",
    name: "Super Smash Bros.",
    system: "n64",
    genre: ["Fighting"],
    releaseYear: 1999,
    region: "NTSC-U",
    coverArt: "/covers/g046.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 30.1,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g047",
    name: "Banjo-Kazooie",
    system: "n64",
    genre: ["Platformer"],
    releaseYear: 1998,
    region: "NTSC-J",
    coverArt: "/covers/g047.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 6.9,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g048",
    name: "Perfect Dark",
    system: "n64",
    genre: ["FPS"],
    releaseYear: 2000,
    region: "PAL",
    coverArt: "/covers/g048.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 8.6,
    playtimeMinutes: 648,
    lastPlayed: "2026-07-20",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g049",
    name: "Star Fox 64",
    system: "n64",
    genre: ["Shooter"],
    releaseYear: 1997,
    region: "NTSC-U",
    coverArt: "/covers/g049.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 13.3,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: true,
    players: 4,
  },
  {
    id: "g050",
    name: "Paper Mario",
    system: "n64",
    genre: ["RPG"],
    releaseYear: 2000,
    region: "PAL",
    coverArt: "/covers/g050.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 26.9,
    playtimeMinutes: 173,
    lastPlayed: "2026-02-13",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g051",
    name: "Donkey Kong 64",
    system: "n64",
    genre: ["Platformer"],
    releaseYear: 1999,
    region: "NTSC-U",
    coverArt: "/covers/g051.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 11.8,
    playtimeMinutes: 111,
    lastPlayed: "2026-04-08",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g052",
    name: "Conker's Bad Fur Day",
    system: "n64",
    genre: ["Action", "Platformer"],
    releaseYear: 2001,
    region: "NTSC-U",
    coverArt: "/covers/g052.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 19.0,
    playtimeMinutes: 2101,
    lastPlayed: "2026-05-12",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g053",
    name: "F-Zero X",
    system: "n64",
    genre: ["Racing"],
    releaseYear: 1998,
    region: "NTSC-U",
    coverArt: "/covers/g053.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 7.0,
    playtimeMinutes: 2393,
    lastPlayed: "2026-05-06",
    favorite: false,
    installed: true,
    players: 4,
  },
  {
    id: "g054",
    name: "Diddy Kong Racing",
    system: "n64",
    genre: ["Racing"],
    releaseYear: 1997,
    region: "PAL",
    coverArt: "/covers/g054.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 9.3,
    playtimeMinutes: 2109,
    lastPlayed: "2026-06-14",
    favorite: true,
    installed: true,
    players: 1,
  },
  {
    id: "g055",
    name: "1080° Snowboarding",
    system: "n64",
    genre: ["Sports"],
    releaseYear: 1998,
    region: "NTSC-U",
    coverArt: "/covers/g055.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 19.1,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: false,
    players: 1,
  },
  {
    id: "g056",
    name: "Wave Race 64",
    system: "n64",
    genre: ["Sports", "Racing"],
    releaseYear: 1996,
    region: "PAL",
    coverArt: "/covers/g056.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 29.2,
    playtimeMinutes: 1300,
    lastPlayed: "2026-06-20",
    favorite: false,
    installed: true,
    players: 2,
  },
  {
    id: "g057",
    name: "Pokémon Stadium",
    system: "n64",
    genre: ["Strategy"],
    releaseYear: 1999,
    region: "NTSC-J",
    coverArt: "/covers/g057.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 14.6,
    playtimeMinutes: 536,
    lastPlayed: "2026-05-18",
    favorite: true,
    installed: true,
    players: 1,
  },
  {
    id: "g058",
    name: "Kirby 64: The Crystal Shards",
    system: "n64",
    genre: ["Platformer"],
    releaseYear: 2000,
    region: "NTSC-J",
    coverArt: "/covers/g058.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 26.0,
    playtimeMinutes: 16,
    lastPlayed: "2026-07-18",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g059",
    name: "Metroid Prime",
    system: "gamecube",
    genre: ["FPS", "Adventure"],
    releaseYear: 2002,
    region: "NTSC-U",
    coverArt: "https://cdn2.steamgriddb.com/thumb/16ed63f1f94f558cfbffed53ce14a7fb.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1256,
    playtimeMinutes: 1826,
    lastPlayed: "2026-08-15",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g060",
    name: "Super Smash Bros. Melee",
    system: "gamecube",
    genre: ["Fighting"],
    releaseYear: 2001,
    region: "NTSC-U",
    coverArt: "/covers/g060.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 864,
    playtimeMinutes: 1387,
    lastPlayed: "2026-05-17",
    favorite: true,
    installed: true,
    players: 4,
  },
  {
    id: "g061",
    name: "Resident Evil 4",
    system: "gamecube",
    genre: ["Survival Horror"],
    releaseYear: 2005,
    region: "NTSC-U",
    coverArt: "/covers/g061.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1295,
    playtimeMinutes: 204,
    lastPlayed: "2026-03-01",
    favorite: true,
    installed: true,
    players: 1,
  },
  {
    id: "g062",
    name: "The Legend of Zelda: The Wind Waker",
    system: "gamecube",
    genre: ["Action", "Adventure"],
    releaseYear: 2002,
    region: "NTSC-U",
    coverArt: "/covers/g062.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1159,
    playtimeMinutes: 1587,
    lastPlayed: "2026-04-23",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g063",
    name: "Super Mario Sunshine",
    system: "gamecube",
    genre: ["Platformer"],
    releaseYear: 2002,
    region: "PAL",
    coverArt: "/covers/g063.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1187,
    playtimeMinutes: 1756,
    lastPlayed: "2026-02-25",
    favorite: true,
    installed: true,
    players: 1,
  },
  {
    id: "g064",
    name: "Mario Kart: Double Dash!!",
    system: "gamecube",
    genre: ["Racing"],
    releaseYear: 2003,
    region: "NTSC-U",
    coverArt: "/covers/g064.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1294,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: true,
    players: 4,
  },
  {
    id: "g065",
    name: "Pikmin",
    system: "gamecube",
    genre: ["Strategy"],
    releaseYear: 2001,
    region: "NTSC-J",
    coverArt: "https://cdn2.steamgriddb.com/thumb/e3de5b73e5c194f5e31c6d6087ee631a.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1129,
    playtimeMinutes: 1314,
    lastPlayed: "2026-09-18",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g066",
    name: "Pikmin 2",
    system: "gamecube",
    genre: ["Strategy"],
    releaseYear: 2004,
    region: "NTSC-U",
    coverArt: "https://cdn2.steamgriddb.com/thumb/63fdae53223bbe821141173cbc090f34.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 881,
    playtimeMinutes: 666,
    lastPlayed: "2026-09-15",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g067",
    name: "F-Zero GX",
    system: "gamecube",
    genre: ["Racing"],
    releaseYear: 2003,
    region: "NTSC-U",
    coverArt: "/covers/g067.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1008,
    playtimeMinutes: 2150,
    lastPlayed: "2026-05-25",
    favorite: false,
    installed: true,
    players: 4,
  },
  {
    id: "g068",
    name: "Luigi's Mansion",
    system: "gamecube",
    genre: ["Action", "Adventure"],
    releaseYear: 2001,
    region: "NTSC-U",
    coverArt: "/covers/g068.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1186,
    playtimeMinutes: 345,
    lastPlayed: "2026-06-18",
    favorite: true,
    installed: true,
    players: 1,
  },
  {
    id: "g069",
    name: "Animal Crossing",
    system: "gamecube",
    genre: ["Simulation"],
    releaseYear: 2001,
    region: "PAL",
    coverArt: "/covers/g069.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1080,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g070",
    name: "Star Fox Adventures",
    system: "gamecube",
    genre: ["Action", "Adventure"],
    releaseYear: 2002,
    region: "NTSC-J",
    coverArt: "/covers/g070.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 973,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g071",
    name: "Eternal Darkness: Sanity's Requiem",
    system: "gamecube",
    genre: ["Survival Horror"],
    releaseYear: 2002,
    region: "PAL",
    coverArt: "/covers/g071.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 946,
    playtimeMinutes: 2373,
    lastPlayed: "2026-01-28",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g072",
    name: "Paper Mario: The Thousand-Year Door",
    system: "gamecube",
    genre: ["RPG"],
    releaseYear: 2004,
    region: "NTSC-U",
    coverArt: "/covers/g072.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1042,
    playtimeMinutes: 2251,
    lastPlayed: "2026-07-18",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g073",
    name: "Fire Emblem: Path of Radiance",
    system: "gamecube",
    genre: ["Strategy", "RPG"],
    releaseYear: 2005,
    region: "PAL",
    coverArt: "/covers/g073.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1207,
    playtimeMinutes: 1391,
    lastPlayed: "2026-01-13",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g074",
    name: "Tales of Symphonia",
    system: "gamecube",
    genre: ["RPG"],
    releaseYear: 2003,
    region: "NTSC-U",
    coverArt: "https://cdn2.steamgriddb.com/thumb/9d0339a83feedcdbf831cd1ccb24301d.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 759,
    playtimeMinutes: 1628,
    lastPlayed: "2026-09-01",
    favorite: false,
    installed: true,
    players: 4,
  },
  {
    id: "g075",
    name: "Viewtiful Joe",
    system: "gamecube",
    genre: ["Action", "Platformer"],
    releaseYear: 2003,
    region: "PAL",
    coverArt: "/covers/g075.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 929,
    playtimeMinutes: 1080,
    lastPlayed: "2026-03-02",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g076",
    name: "Killer7",
    system: "gamecube",
    genre: ["Action", "Shooter"],
    releaseYear: 2005,
    region: "NTSC-U",
    coverArt: "/covers/g076.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 736,
    playtimeMinutes: 350,
    lastPlayed: "2026-07-09",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g077",
    name: "Final Fantasy VII",
    system: "ps1",
    genre: ["RPG"],
    releaseYear: 1997,
    region: "NTSC-U",
    coverArt: "/covers/g077.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 220,
    playtimeMinutes: 179,
    lastPlayed: "2026-02-25",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g078",
    name: "Final Fantasy VIII",
    system: "ps1",
    genre: ["RPG"],
    releaseYear: 1999,
    region: "NTSC-U",
    coverArt: "/covers/g078.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 231,
    playtimeMinutes: 1954,
    lastPlayed: "2026-04-05",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g079",
    name: "Final Fantasy IX",
    system: "ps1",
    genre: ["RPG"],
    releaseYear: 2000,
    region: "NTSC-J",
    coverArt: "/covers/g079.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 287,
    playtimeMinutes: 484,
    lastPlayed: "2026-03-20",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g080",
    name: "Metal Gear Solid",
    system: "ps1",
    genre: ["Stealth", "Action"],
    releaseYear: 1998,
    region: "PAL",
    coverArt: "/covers/g080.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 506,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g081",
    name: "Crash Bandicoot",
    system: "ps1",
    genre: ["Platformer"],
    releaseYear: 1996,
    region: "NTSC-J",
    coverArt: "/covers/g081.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 610,
    playtimeMinutes: 1009,
    lastPlayed: "2026-04-03",
    favorite: true,
    installed: true,
    players: 1,
  },
  {
    id: "g082",
    name: "Crash Bandicoot 2: Cortex Strikes Back",
    system: "ps1",
    genre: ["Platformer"],
    releaseYear: 1997,
    region: "NTSC-U",
    coverArt: "/covers/g082.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 404,
    playtimeMinutes: 2197,
    lastPlayed: "2026-01-12",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g083",
    name: "Spyro the Dragon",
    system: "ps1",
    genre: ["Platformer"],
    releaseYear: 1998,
    region: "PAL",
    coverArt: "/covers/g083.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 394,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g084",
    name: "Resident Evil 2",
    system: "ps1",
    genre: ["Survival Horror"],
    releaseYear: 1998,
    region: "NTSC-U",
    coverArt: "https://cdn2.steamgriddb.com/thumb/281bda7f615b095f3e40f05dfb735202.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 679,
    playtimeMinutes: 641,
    lastPlayed: "2026-08-23",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g085",
    name: "Castlevania: Symphony of the Night",
    system: "ps1",
    genre: ["Action", "Platformer"],
    releaseYear: 1997,
    region: "NTSC-U",
    coverArt: "https://cdn2.steamgriddb.com/thumb/7115d15060517a9146826ff3aae574c4.jpg",
    backdropArt: "https://cdn2.steamgriddb.com/hero/ec5205928d905ea263a69ab15c89e4c6.png",
    fileSizeMB: 455,
    playtimeMinutes: 1995,
    lastPlayed: "2026-09-25",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g086",
    name: "Tekken 3",
    system: "ps1",
    genre: ["Fighting"],
    releaseYear: 1998,
    region: "NTSC-U",
    coverArt: "/covers/g086.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 466,
    playtimeMinutes: 1861,
    lastPlayed: "2026-02-09",
    favorite: true,
    installed: true,
    players: 2,
  },
  {
    id: "g087",
    name: "Tony Hawk's Pro Skater 2",
    system: "ps1",
    genre: ["Sports"],
    releaseYear: 2000,
    region: "NTSC-U",
    coverArt: "/covers/g087.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 209,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: false,
    players: 1,
  },
  {
    id: "g088",
    name: "Gran Turismo",
    system: "ps1",
    genre: ["Racing"],
    releaseYear: 1997,
    region: "PAL",
    coverArt: "/covers/g088.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 215,
    playtimeMinutes: 1146,
    lastPlayed: "2026-06-09",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g089",
    name: "Silent Hill",
    system: "ps1",
    genre: ["Survival Horror"],
    releaseYear: 1999,
    region: "NTSC-U",
    coverArt: "/covers/g089.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 576,
    playtimeMinutes: 1965,
    lastPlayed: "2026-04-23",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g090",
    name: "Tomb Raider",
    system: "ps1",
    genre: ["Action", "Adventure"],
    releaseYear: 1996,
    region: "NTSC-J",
    coverArt: "/covers/g090.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 384,
    playtimeMinutes: 1011,
    lastPlayed: "2026-07-23",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g091",
    name: "Twisted Metal 2",
    system: "ps1",
    genre: ["Vehicular Combat"],
    releaseYear: 1996,
    region: "NTSC-U",
    coverArt: "https://cdn2.steamgriddb.com/thumb/6c2335954b5f56e9cb123f27c69f4a80.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 251,
    playtimeMinutes: 1456,
    lastPlayed: "2026-09-11",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g092",
    name: "Grand Theft Auto",
    system: "ps1",
    genre: ["Action"],
    releaseYear: 1997,
    region: "NTSC-J",
    coverArt: "https://cdn2.steamgriddb.com/thumb/2f6a78b8f64630d5e8191a7be8ccad3a.jpg",
    backdropArt: "https://cdn2.steamgriddb.com/hero/ef2a4be5473ab0b3cc286e67b1f59f44.png",
    fileSizeMB: 266,
    playtimeMinutes: 773,
    lastPlayed: "2026-09-25",
    favorite: true,
    installed: true,
    players: 1,
  },
  {
    id: "g093",
    name: "Parasite Eve",
    system: "ps1",
    genre: ["RPG", "Survival Horror"],
    releaseYear: 1998,
    region: "NTSC-U",
    coverArt: "https://cdn2.steamgriddb.com/thumb/a292a4b3657cf531490ed1dfa50d02d4.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 278,
    playtimeMinutes: 1174,
    lastPlayed: "2026-09-20",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g094",
    name: "Vagrant Story",
    system: "ps1",
    genre: ["RPG"],
    releaseYear: 2000,
    region: "NTSC-U",
    coverArt: "/covers/g094.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 420,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g095",
    name: "Chrono Cross",
    system: "ps1",
    genre: ["RPG"],
    releaseYear: 1999,
    region: "NTSC-U",
    coverArt: "/covers/g095.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 275,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g096",
    name: "Suikoden II",
    system: "ps1",
    genre: ["RPG"],
    releaseYear: 1999,
    region: "NTSC-U",
    coverArt: "/covers/g096.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 364,
    playtimeMinutes: 65,
    lastPlayed: "2026-08-04",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g097",
    name: "Shadow of the Colossus",
    system: "ps2",
    genre: ["Action", "Adventure"],
    releaseYear: 2005,
    region: "NTSC-J",
    coverArt: "/covers/g097.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 2926,
    playtimeMinutes: 1971,
    lastPlayed: "2026-05-28",
    favorite: true,
    installed: true,
    players: 1,
  },
  {
    id: "g098",
    name: "God of War",
    system: "ps2",
    genre: ["Action", "Hack and Slash"],
    releaseYear: 2005,
    region: "NTSC-U",
    coverArt: "/covers/g098.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1747,
    playtimeMinutes: 626,
    lastPlayed: "2026-01-05",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g099",
    name: "Kingdom Hearts",
    system: "ps2",
    genre: ["Action", "RPG"],
    releaseYear: 2002,
    region: "NTSC-J",
    coverArt: "/covers/g099.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 3258,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g100",
    name: "Final Fantasy X",
    system: "ps2",
    genre: ["RPG"],
    releaseYear: 2001,
    region: "PAL",
    coverArt: "https://cdn2.steamgriddb.com/thumb/6d03025cb988ab590388015e6321df2c.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 3207,
    playtimeMinutes: 1860,
    lastPlayed: "2026-09-13",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g101",
    name: "Metal Gear Solid 3: Snake Eater",
    system: "ps2",
    genre: ["Stealth", "Action"],
    releaseYear: 2004,
    region: "NTSC-U",
    coverArt: "/covers/g101.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 2112,
    playtimeMinutes: 421,
    lastPlayed: "2026-01-20",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g102",
    name: "Grand Theft Auto: San Andreas",
    system: "ps2",
    genre: ["Action"],
    releaseYear: 2004,
    region: "NTSC-U",
    coverArt: "/covers/g102.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1718,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g103",
    name: "Devil May Cry",
    system: "ps2",
    genre: ["Action", "Hack and Slash"],
    releaseYear: 2001,
    region: "PAL",
    coverArt: "https://cdn2.steamgriddb.com/thumb/c7c637057b01f03dd44458f86eb12c34.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 3539,
    playtimeMinutes: 148,
    lastPlayed: "2026-08-10",
    favorite: true,
    installed: true,
    players: 1,
  },
  {
    id: "g104",
    name: "Devil May Cry 3: Dante's Awakening",
    system: "ps2",
    genre: ["Action", "Hack and Slash"],
    releaseYear: 2005,
    region: "NTSC-J",
    coverArt: "/covers/g104.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 2267,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g105",
    name: "Persona 4",
    system: "ps2",
    genre: ["RPG"],
    releaseYear: 2008,
    region: "NTSC-U",
    coverArt: "/covers/g105.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 4134,
    playtimeMinutes: 485,
    lastPlayed: "2026-04-14",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g106",
    name: "Okami",
    system: "ps2",
    genre: ["Action", "Adventure"],
    releaseYear: 2006,
    region: "NTSC-J",
    coverArt: "/covers/g106.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 2392,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g107",
    name: "Ratchet & Clank",
    system: "ps2",
    genre: ["Platformer", "Shooter"],
    releaseYear: 2002,
    region: "NTSC-J",
    coverArt: "/covers/g107.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 4234,
    playtimeMinutes: 1934,
    lastPlayed: "2026-08-04",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g108",
    name: "Jak and Daxter: The Precursor Legacy",
    system: "ps2",
    genre: ["Platformer"],
    releaseYear: 2001,
    region: "NTSC-U",
    coverArt: "/covers/g108.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 3251,
    playtimeMinutes: 178,
    lastPlayed: "2026-08-03",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g109",
    name: "Tekken 5",
    system: "ps2",
    genre: ["Fighting"],
    releaseYear: 2004,
    region: "NTSC-U",
    coverArt: "/covers/g109.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 3924,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: false,
    players: 1,
  },
  {
    id: "g110",
    name: "Silent Hill 2",
    system: "ps2",
    genre: ["Survival Horror"],
    releaseYear: 2001,
    region: "NTSC-J",
    coverArt: "/covers/g110.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 2026,
    playtimeMinutes: 2140,
    lastPlayed: "2026-03-16",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g111",
    name: "Guitar Hero II",
    system: "ps2",
    genre: ["Rhythm"],
    releaseYear: 2006,
    region: "NTSC-U",
    coverArt: "/covers/g111.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 3443,
    playtimeMinutes: 1940,
    lastPlayed: "2026-08-03",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g112",
    name: "Tony Hawk's Underground",
    system: "ps2",
    genre: ["Sports"],
    releaseYear: 2003,
    region: "NTSC-U",
    coverArt: "https://cdn2.steamgriddb.com/thumb/ccf63039aff12f2d69d0fdf772644e24.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 2819,
    playtimeMinutes: 1655,
    lastPlayed: "2026-08-10",
    favorite: false,
    installed: true,
    players: 2,
  },
  {
    id: "g113",
    name: "Katamari Damacy",
    system: "ps2",
    genre: ["Puzzle"],
    releaseYear: 2004,
    region: "PAL",
    coverArt: "/covers/g113.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 4021,
    playtimeMinutes: 2122,
    lastPlayed: "2026-07-28",
    favorite: false,
    installed: true,
    players: 2,
  },
  {
    id: "g114",
    name: "Ico",
    system: "ps2",
    genre: ["Action", "Adventure"],
    releaseYear: 2001,
    region: "PAL",
    coverArt: "/covers/g114.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 3306,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g115",
    name: "Dragon Quest VIII",
    system: "ps2",
    genre: ["RPG"],
    releaseYear: 2004,
    region: "PAL",
    coverArt: "/covers/g115.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 2771,
    playtimeMinutes: 1108,
    lastPlayed: "2026-01-07",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g116",
    name: "Gran Turismo 4",
    system: "ps2",
    genre: ["Racing"],
    releaseYear: 2004,
    region: "NTSC-U",
    coverArt: "/covers/g116.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 3266,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: false,
    players: 1,
  },
  {
    id: "g117",
    name: "Sonic the Hedgehog",
    system: "genesis",
    genre: ["Platformer"],
    releaseYear: 1991,
    region: "PAL",
    coverArt: "/covers/g117.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1.8,
    playtimeMinutes: 1686,
    lastPlayed: "2026-01-18",
    favorite: true,
    installed: true,
    players: 1,
  },
  {
    id: "g118",
    name: "Sonic the Hedgehog 2",
    system: "genesis",
    genre: ["Platformer"],
    releaseYear: 1992,
    region: "NTSC-U",
    coverArt: "/covers/g118.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1.7,
    playtimeMinutes: 1210,
    lastPlayed: "2026-03-16",
    favorite: false,
    installed: true,
    players: 2,
  },
  {
    id: "g119",
    name: "Sonic 3 & Knuckles",
    system: "genesis",
    genre: ["Platformer"],
    releaseYear: 1994,
    region: "NTSC-U",
    coverArt: "/covers/g119.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1.8,
    playtimeMinutes: 795,
    lastPlayed: "2026-03-13",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g120",
    name: "Streets of Rage 2",
    system: "genesis",
    genre: ["Beat em up"],
    releaseYear: 1992,
    region: "NTSC-U",
    coverArt: "/covers/g120.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1.5,
    playtimeMinutes: 2094,
    lastPlayed: "2026-07-11",
    favorite: true,
    installed: true,
    players: 2,
  },
  {
    id: "g121",
    name: "Streets of Rage 3",
    system: "genesis",
    genre: ["Beat em up"],
    releaseYear: 1994,
    region: "NTSC-U",
    coverArt: "https://cdn2.steamgriddb.com/thumb/6898af60f246563ee232e2d384613504.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1.0,
    playtimeMinutes: 1376,
    lastPlayed: "2026-08-12",
    favorite: false,
    installed: true,
    players: 2,
  },
  {
    id: "g122",
    name: "Golden Axe",
    system: "genesis",
    genre: ["Beat em up"],
    releaseYear: 1989,
    region: "PAL",
    coverArt: "/covers/g122.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.3,
    playtimeMinutes: 1583,
    lastPlayed: "2026-04-19",
    favorite: true,
    installed: true,
    players: 2,
  },
  {
    id: "g123",
    name: "Gunstar Heroes",
    system: "genesis",
    genre: ["Run and Gun"],
    releaseYear: 1993,
    region: "PAL",
    coverArt: "/covers/g123.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.8,
    playtimeMinutes: 166,
    lastPlayed: "2026-03-16",
    favorite: true,
    installed: true,
    players: 1,
  },
  {
    id: "g124",
    name: "Phantasy Star IV",
    system: "genesis",
    genre: ["RPG"],
    releaseYear: 1993,
    region: "NTSC-U",
    coverArt: "/covers/g124.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.2,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: false,
    players: 1,
  },
  {
    id: "g125",
    name: "Shining Force II",
    system: "genesis",
    genre: ["Strategy", "RPG"],
    releaseYear: 1993,
    region: "PAL",
    coverArt: "/covers/g125.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1.3,
    playtimeMinutes: 1938,
    lastPlayed: "2026-03-03",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g126",
    name: "Castlevania: Bloodlines",
    system: "genesis",
    genre: ["Action", "Platformer"],
    releaseYear: 1994,
    region: "PAL",
    coverArt: "/covers/g126.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1.5,
    playtimeMinutes: 2200,
    lastPlayed: "2026-06-28",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g127",
    name: "ToeJam & Earl",
    system: "genesis",
    genre: ["Adventure"],
    releaseYear: 1991,
    region: "NTSC-U",
    coverArt: "/covers/g127.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.7,
    playtimeMinutes: 295,
    lastPlayed: "2026-01-20",
    favorite: true,
    installed: true,
    players: 1,
  },
  {
    id: "g128",
    name: "Comix Zone",
    system: "genesis",
    genre: ["Beat em up"],
    releaseYear: 1995,
    region: "NTSC-U",
    coverArt: "/covers/g128.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1.8,
    playtimeMinutes: 426,
    lastPlayed: "2026-02-25",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g129",
    name: "Ecco the Dolphin",
    system: "genesis",
    genre: ["Adventure"],
    releaseYear: 1992,
    region: "NTSC-J",
    coverArt: "/covers/g129.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1.2,
    playtimeMinutes: 1483,
    lastPlayed: "2026-01-10",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g130",
    name: "Altered Beast",
    system: "genesis",
    genre: ["Beat em up"],
    releaseYear: 1988,
    region: "NTSC-U",
    coverArt: "/covers/g130.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1.3,
    playtimeMinutes: 732,
    lastPlayed: "2026-03-06",
    favorite: true,
    installed: true,
    players: 1,
  },
  {
    id: "g131",
    name: "Vectorman",
    system: "genesis",
    genre: ["Platformer"],
    releaseYear: 1995,
    region: "PAL",
    coverArt: "/covers/g131.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1.4,
    playtimeMinutes: 1903,
    lastPlayed: "2026-03-08",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g132",
    name: "Earthworm Jim",
    system: "genesis",
    genre: ["Platformer"],
    releaseYear: 1994,
    region: "PAL",
    coverArt: "https://cdn2.steamgriddb.com/thumb/239b93034dcee89c657283c522cdc124.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1.3,
    playtimeMinutes: 317,
    lastPlayed: "2026-09-06",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g133",
    name: "Contra: Hard Corps",
    system: "genesis",
    genre: ["Run and Gun"],
    releaseYear: 1994,
    region: "PAL",
    coverArt: "https://cdn2.steamgriddb.com/thumb/92c08ca1d74fb2a5f1ad221067db1a07.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 1.1,
    playtimeMinutes: 1252,
    lastPlayed: "2026-08-28",
    favorite: true,
    installed: true,
    players: 1,
  },
  {
    id: "g134",
    name: "Mortal Kombat",
    system: "genesis",
    genre: ["Fighting"],
    releaseYear: 1992,
    region: "NTSC-J",
    coverArt: "/covers/g134.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 0.9,
    playtimeMinutes: 1224,
    lastPlayed: "2026-05-23",
    favorite: true,
    installed: true,
    players: 1,
  },
  {
    id: "g135",
    name: "Pokémon Emerald",
    system: "gba",
    genre: ["RPG"],
    releaseYear: 2004,
    region: "NTSC-U",
    coverArt: "/covers/g135.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 25.3,
    playtimeMinutes: 2049,
    lastPlayed: "2026-01-20",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g136",
    name: "Pokémon FireRed",
    system: "gba",
    genre: ["RPG"],
    releaseYear: 2004,
    region: "NTSC-U",
    coverArt: "/covers/g136.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 23.6,
    playtimeMinutes: 793,
    lastPlayed: "2026-06-08",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g137",
    name: "Metroid Fusion",
    system: "gba",
    genre: ["Action", "Adventure"],
    releaseYear: 2002,
    region: "NTSC-U",
    coverArt: "/covers/g137.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 5.9,
    playtimeMinutes: 1820,
    lastPlayed: "2026-01-10",
    favorite: true,
    installed: true,
    players: 1,
  },
  {
    id: "g138",
    name: "Metroid: Zero Mission",
    system: "gba",
    genre: ["Action", "Adventure"],
    releaseYear: 2004,
    region: "NTSC-J",
    coverArt: "/covers/g138.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 31.1,
    playtimeMinutes: 837,
    lastPlayed: "2026-07-06",
    favorite: true,
    installed: true,
    players: 1,
  },
  {
    id: "g139",
    name: "Advance Wars",
    system: "gba",
    genre: ["Strategy"],
    releaseYear: 2001,
    region: "NTSC-U",
    coverArt: "/covers/g139.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 16.5,
    playtimeMinutes: 688,
    lastPlayed: "2026-05-27",
    favorite: true,
    installed: true,
    players: 1,
  },
  {
    id: "g140",
    name: "Advance Wars 2: Black Hole Rising",
    system: "gba",
    genre: ["Strategy"],
    releaseYear: 2003,
    region: "NTSC-U",
    coverArt: "/covers/g140.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 24.6,
    playtimeMinutes: 486,
    lastPlayed: "2026-06-26",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g141",
    name: "Fire Emblem",
    system: "gba",
    genre: ["Strategy", "RPG"],
    releaseYear: 2003,
    region: "NTSC-J",
    coverArt: "/covers/g141.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 2.4,
    playtimeMinutes: 2297,
    lastPlayed: "2026-07-28",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g142",
    name: "The Legend of Zelda: The Minish Cap",
    system: "gba",
    genre: ["Action", "Adventure"],
    releaseYear: 2004,
    region: "NTSC-U",
    coverArt: "/covers/g142.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 24.5,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g143",
    name: "Golden Sun",
    system: "gba",
    genre: ["RPG"],
    releaseYear: 2001,
    region: "NTSC-U",
    coverArt: "/covers/g143.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 30.3,
    playtimeMinutes: 972,
    lastPlayed: "2026-06-04",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g144",
    name: "Golden Sun: The Lost Age",
    system: "gba",
    genre: ["RPG"],
    releaseYear: 2002,
    region: "PAL",
    coverArt: "/covers/g144.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 23.0,
    playtimeMinutes: 273,
    lastPlayed: "2026-04-21",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g145",
    name: "Mario Kart: Super Circuit",
    system: "gba",
    genre: ["Racing"],
    releaseYear: 2001,
    region: "NTSC-U",
    coverArt: "/covers/g145.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 3.1,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: true,
    players: 4,
  },
  {
    id: "g146",
    name: "Super Mario Advance 4: Super Mario Bros. 3",
    system: "gba",
    genre: ["Platformer"],
    releaseYear: 2003,
    region: "PAL",
    coverArt: "/covers/g146.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 6.1,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: false,
    players: 1,
  },
  {
    id: "g147",
    name: "Kirby & the Amazing Mirror",
    system: "gba",
    genre: ["Platformer"],
    releaseYear: 2004,
    region: "NTSC-U",
    coverArt: "https://cdn2.steamgriddb.com/thumb/978e1dbe92d1bde18868c5a59282844a.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 27.0,
    playtimeMinutes: 647,
    lastPlayed: "2026-09-14",
    favorite: false,
    installed: true,
    players: 4,
  },
  {
    id: "g148",
    name: "Castlevania: Aria of Sorrow",
    system: "gba",
    genre: ["Action", "Platformer"],
    releaseYear: 2003,
    region: "NTSC-U",
    coverArt: "/covers/g148.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 15.3,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g149",
    name: "Castlevania: Harmony of Dissonance",
    system: "gba",
    genre: ["Action", "Platformer"],
    releaseYear: 2002,
    region: "PAL",
    coverArt: "/covers/g149.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 12.8,
    playtimeMinutes: 1519,
    lastPlayed: "2026-02-22",
    favorite: false,
    installed: true,
    players: 1,
  },
  {
    id: "g150",
    name: "F-Zero: Maximum Velocity",
    system: "gba",
    genre: ["Racing"],
    releaseYear: 2001,
    region: "NTSC-U",
    coverArt: "/covers/g150.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 21.2,
    playtimeMinutes: 1877,
    lastPlayed: "2026-02-28",
    favorite: true,
    installed: true,
    players: 1,
  },
  {
    id: "g151",
    name: "WarioWare, Inc.: Mega Microgame$",
    system: "gba",
    genre: ["Party"],
    releaseYear: 2003,
    region: "NTSC-J",
    coverArt: "/covers/g151.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 18.6,
    playtimeMinutes: 2327,
    lastPlayed: "2026-04-05",
    favorite: true,
    installed: true,
    players: 1,
  },
  {
    id: "g152",
    name: "Mega Man Zero",
    system: "gba",
    genre: ["Action", "Platformer"],
    releaseYear: 2002,
    region: "NTSC-U",
    coverArt: "/covers/g152.jpg",
    backdropArt: "/backdrops/g001.jpg",
    fileSizeMB: 11.9,
    playtimeMinutes: 0,
    lastPlayed: null,
    favorite: false,
    installed: false,
    players: 1,
  },
];
